### ISSUE TITLE
cannot load such file -- puppet_x/net_dev/eos_api

### ISSUE THREAD

**Issue by greenpau** [arista-eosplus/puppet-netdev#17]
Configuring:

```
  network_interface { 'Ethernet20':
    description => 'PUPPET_TEST',
    duplex      => 'auto',
    enable      => 'true',
    speed       => 'auto',
  }
```

The issue presented itself when running `bundle exec rake diffspec`:

```
 Could not autoload puppet/type/network_interface: Could not autoload puppet/provider/network_interface/eos: cannot load such file -- puppet_x/net_dev/eos_api on node ARISTA01
```

Had to make the following change in `modules/netdev_stdlib_eos/lib/puppet/provider/network_interface/eos.rb` for it to work:

```
require 'puppet/type'
#require 'puppet_x/net_dev/eos_api'

begin
  require "puppet_x/net_dev/eos_api"
rescue LoadError => detail
  require 'pathname' # JJM WORK_AROUND #14073
  module_base = Pathname.new(__FILE__).dirname
  require module_base + "../../../" + "puppet_x/net_dev/eos_api"
end
```

I also added the following line to `.gemspec`:

```
    gem.add_dependency 'rbeapi', '~> 0.1', '>= 0.1.0'
```

See also: https://projects.puppetlabs.com/issues/14149

The idea came from [puppetlabs/puppetlabs-registry](https://github.com/puppetlabs/puppetlabs-registry/blob/master/lib/puppet/provider/registry_key/registry.rb)

Please assist.

**Comment by greenpau** [comment]
@privateip , the syntax `newparam(:name, namevar: true) do` is new with ruby `1.9.x`.

During catalog compilation, puppet uses the above code. As such if an organization runs RHEL (which is Ruby `1.8.7`), the compilation will fail with the below error:

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not autoload puppet/type/domain_name: /opt/puppet/modules/netdev_stdlib/lib/puppet/type/domain_name.rb:8: syntax error, unexpected ':', expecting ')'
  newparam(:name, namevar: true) do
                          ^
/opt/puppet/modules/netdev_stdlib/lib/puppet/type/domain_name.rb:17: syntax error, unexpected kEND, expecting $end on node NY-FW01
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

Therefore, there is a limitation to using this module, i.e. Puppet Master with `1.9.x` code.

**Comment by privateip** [comment]
Thats correct, the minimum requirement is Ruby 1.9.x
